# Generated by Django 4.0.6 on 2022-08-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ManyToManyField(null=True, to='posts.topic'),
        ),
    ]
