# Generated by Django 4.0.6 on 2022-08-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ManyToManyField(blank=True, null=True, to='posts.topic'),
        ),
    ]
