# Generated by Django 4.0.6 on 2022-08-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_topic',
        ),
        migrations.AddField(
            model_name='post',
            name='post_topic',
            field=models.ManyToManyField(blank=True, null=True, to='posts.topic'),
        ),
    ]
