# Generated by Django 4.0.6 on 2022-08-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_alter_profile_background_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_colors',
            field=models.CharField(choices=[('CEC8D2', 'color1'), ('FFF5EB', 'color2'), ('FFE0D1', 'color3'), ('C7D8EB', 'color4'), ('E5DECD', 'color5')], default='CEC8D2', max_length=6, null=True),
        ),
    ]
